source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.baidao.com/ios/ytx-pod-specs.git'

target 'DXRouter_Example' do
  pod 'DXRouter', :path => '../'
  pod 'Masonry', '~> 1.0.2'
  target 'DXRouter_Tests' do

    
  end
end
