# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'ForRegexTest' do
pod 'ReactiveCocoa', '~> 2.5'
end

target 'ForRegexTestTests' do

end

target 'ForRegexTestUITests' do

end

