# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'OpenGL' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OpenGL
  pod 'ReactiveCocoa','~>2.5'
  pod 'FMDB'
  pod 'Aspects'

  target 'OpenGLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OpenGLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
